### ISSUE TITLE
Problem with initial backup after loading extension

### ISSUE THREAD

**Issue by jmh108** [itcon-pty-au/typingmind-cloud-backup#2]
I get the following error log and the script runs in a loop, any ideas?

> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (typingmind-backup.json, line 0)
> [Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (typingmind-backup.json, line 0)
> [Debug] Extensions loaded. Ignore error events (_app-a67b9cbe4b6e730f.js, line 1)
> [Error] Unhandled Promise Rejection: BadDigest: The Content-MD5 you specified did not match what we received.
> 	(anonyme Funktion) (s3.js:261)
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (typingmind-backup.json, line 0)

**Comment by itcon-pty-au** [comment]
The current version backups up to S3 every 5 seconds. You may be mistaking this for a loop. After configuring the AWS values, did you click "Import from S3" button?

**Comment by jmh108** [comment]
I'm getting the:
> [Error] Unhandled Promise Rejection: BadDigest: The Content-MD5 you specified did not match what we received.
> (anonyme Funktion) (s3.js:261)
when I click on "Export to S3"

So the extension fails to initiate the first Export to S3

The alert I get is:
> "Backup file not found in S3! Run an adhoc 'Export to S3' first."
The alert runs in a kind of loop, probably the backup frequency you mentioned. 

> [Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (typingmind-backup.json, line 0)

**Comment by itcon-pty-au** [comment]
@jmh108 - This should be fixed now. Can you try once again and feedback please?

**Comment by jmh108** [comment]
Thank you.
I couldn't make it work on the machine I tried first, but the "loop" was not running anymore after your fix, I still got the BadDigest Error. 
I initiated the backup on a different machine, and I worked out fine this time.

**Comment by itcon-pty-au** [comment]
Thanks @jmh108 for the confirmation. I'll close this issue.
