### ISSUE TITLE
When entering the website, the old backup will be restored.

### ISSUE THREAD

**Issue by Ariesdessert** [itcon-pty-au/typingmind-cloud-backup#3]
Every time I enter the website, it restores the old backup. I try to create a new chat and then click the Export S3 button, or wait for 1 minute for it to automatically backup. However, when I enter again or refresh the page, it still restores the old backup.

**Comment by itcon-pty-au** [comment]
It could be a caching thing with your browser. Try doing a Ctrl + F5 and see if the force refresh resolves it.

**Comment by Ariesdessert** [comment]
Force refresh doesn't seem to work. Notably, if I delete a chat and then click the "Export to S3" button, followed by a refresh or force refresh, that deleted chat history will be restored within seconds.

**Comment by itcon-pty-au** [comment]
Thanks for checking.

Can you ensure all other instances of the chat (where this extension is loaded) across all your devices are closed? And see if the issue reoccurs. Ideally backup to S3 should happen only from the active window. But they may be some bug causing it to push updates even if the window is inactive. If that is the case, updates may be pushed from another browser tab that you may no longer be using. Can you check if this is the case?

**Comment by Ariesdessert** [comment]
I'm using Firefox Nightly Android, and after your reminder, I discovered there were other, redundant, inactive, and unused Typingmind tabs (seemingly not loaded) in Firefox Nightly Android, which indeed caused this issue. This problem should now be resolved. Thank you for your continued help.

**Comment by itcon-pty-au** [comment]
Thanks for checking and confirming. I will keep this issue open for now. I will work on getting a fix in soon for this.

**Comment by Ariesdessert** [comment]
Okay. However, it's regrettable that after testing again just now, despite ensuring only one tab was kept open, the issue still occurred again.

**Comment by itcon-pty-au** [comment]
The fix has been applied in the beta repo. I will port it to the main repo after a week once I am able to do sufficient testing. You are welcome to test it out. If you choose to, make sure you use the extension URL as "https://itcon-pty-au.github.io/typingmind-cloud-backup-beta/s3.js". ( This is the Beta version )

**Comment by Ariesdessert** [comment]
Okay, thank you for the fix. Currently, everything is working fine with the Beta version.

**Comment by Ariesdessert** [comment]
Unfortunately, this problem has appeared again.

**Comment by Ariesdessert** [comment]
The beta version still has issues. In Firefox Nightly Android's about:config, setting browser.cache.disk.enable to false seems to resolve this problem.

**Comment by Ariesdessert** [comment]
Okay, so far setting browser.cache.disk.enable to false has been effective in resolving this issue.
In previous tests, setting browser.cache.disk.enable to false resolved this issue, but setting browser.cache.memory.enable to false did not solve the problem.

**Comment by itcon-pty-au** [comment]
Ill close this for now and lets reopen it if it resurfaces.

**Comment by Ariesdessert** [comment]
OK, thank you for making such a useful extension. I tested that this issue still occurs, but it works normally after setting browser.cache.disk.enable to false (using Firefox Nightly). I will keep browser.cache.disk.enable in false state for normal use. I suspect this might be a Firefox issue. Because it seems no one else has encountered this problem. It seems most people are using Chromium-based browsers.
