### ISSUE TITLE
export to S3 failed

### ISSUE THREAD

**Issue by ZefanHu** [itcon-pty-au/typingmind-cloud-backup#4]
I clear the S3 first, then I tested synchronizing smaller files and Backup succeeded, but I imported the entire history backup and it failed. My entire history is about 20 MB in size.           

![image](https://github.com/user-attachments/assets/051fff8d-1b29-48df-9924-ee1cf2ae2975)

**Comment by itcon-pty-au** [comment]
@ZefanHu - Thanks for trying this out. How was this 20MB file created in the first place? Via this extension or via the original typingmind backup feature? Note that import will work only if the file was generated by this extension.

**Comment by ZefanHu** [comment]
> @ZefanHu - Thanks for trying this out. How was this 20MB file created in the first place? Via this extension or via the original typingmind backup feature? Note that import will work only if the file was generated by this extension.

Thank you for your help! Just to clarify, this 20MB history file was exported using the “export” button on the Typingmind website. Does that mean it's currently impossible to back it up? Is there any way I could manually modify the format of the history file to make it work? I’d greatly appreciate any advice you could provide. Thanks again!

**Comment by itcon-pty-au** [comment]
Once you configure the extension, click on the "Export to S3" button. (Refer attached)

This should create the full backup file in S3.
________________________________

**Comment by itcon-pty-au** [comment]
![Screenshot_20241114-020951](https://github.com/user-attachments/assets/1581b742-422b-4bc1-8064-235bd92fd9a5)

Once you configure the extension, click on the "Export to S3" button. This should create the full backup file in S3.

**Comment by ZefanHu** [comment]
> This should create the full backup file in S3.

Thank you! I successfully configured the extension, and the backup to S3 is working. However, the JSON file format backed up to S3 by the extension is different from the history file format exported from the Typingmind website. Does this mean that the history file exported from the website cannot be re-imported and backed up to S3 via the extension?

**Comment by itcon-pty-au** [comment]
The extension automatically does the sync, so you need not manually import the backup each time. 

However, if you need an ad-hoc import, use the "Import to S3" button in the extension configuration form to automatically import the backup from S3.

Guess I should create a detailed document on how the extension works. Will do that soon.
