### ISSUE TITLE
Backup icon disappeared after latest TypingMind update

### ISSUE THREAD

**Issue by AutonomousWork** [itcon-pty-au/typingmind-cloud-backup#9]
Backup icon no longer visible after latest typingmind update over Thanksgiving weekend. Sync not working either. Removal of extension does not remove artifact in browser inspector that continues to include a pointer to s3.js

**Comment by AutonomousWork** [comment]
I'm still running into issues unfortunately. The icon briefly appears, and successfully point to config, after adding the extension. The icon is disappears again on PWA close. I've tried on both Edge (Desktop) and iPadOS 18.1

**Comment by AutonomousWork** [comment]
Back in business! I removed PWAs on all devices and cleared site data for typingmind.com. Fresh install with your new code worked perfectly and I was able to restore from backup. Thanks again for this extension

**Comment by itcon-pty-au** [comment]
Thank you for the confirmation.

**Comment by Shigeki1120** [comment]
@itcon-pty-au It just started happening today after the latest update

**Comment by itcon-pty-au** [comment]
> @itcon-pty-au It just started happening today after the latest update. This is the error: Uncaught SyntaxError: Unexpected end of input (at s3.js:1439:1). I did a pr #15

Thank you @Shigeki1120 . Merged the PR.
